import { useMemo, useState } from "react";
import { Bell, Check, ChevronRight, Home, LogOut, Network, Settings, ShieldCheck, Smartphone, User } from "lucide-react";
import { Brand } from "../components/Brand";
import { Button, Card, EmptyState, Field, StatusBadge } from "../components/UI";
import { formatDate, initials } from "../helpers";
import { useAppState } from "../state/AppStateProvider";

type MobilePage = "Home" | "Alerts" | "My Tree" | "Profile";

function MobileLogin({ onSwitch }: { onSwitch(): void }) {
  const { state, dispatch } = useAppState(); const [phone, setPhone] = useState(""); const [error, setError] = useState("");
  const submit = (event: React.FormEvent) => { event.preventDefault(); const normalized = phone.replace(/\D/g, ""); const contact = state.contacts.find((item) => item.phone.replace(/\D/g, "") === normalized); if (!contact) { setError("No contact matches that number. Ask an administrator to add it first."); return; } dispatch({ type: "MOBILE_LOGIN", contactId: contact.id }); };
  return <main className="mobile-auth"><section><Brand/><div className="mobile-auth-copy"><span><Smartphone/></span><h1>Receive and confirm official alerts.</h1><p>Sign in using a phone number already saved by an administrator.</p></div></section><form onSubmit={submit}><h2>Mobile sign in</h2><p>No verification message is sent in this local build.</p><Field label="Mobile number" type="tel" value={phone} onChange={(e) => { setPhone(e.target.value); setError(""); }} placeholder="Enter a saved contact number" required/>{error && <div className="form-error">{error}</div>}<Button type="submit" disabled={!phone.trim()}>Continue</Button><Button type="button" variant="ghost" onClick={onSwitch}>Open admin workspace</Button>{state.contacts.length === 0 && <div className="inline-notice">There are no contacts yet. Open the admin workspace and add one.</div>}</form></main>;
}

export function MobileApp({ onSwitch }: { onSwitch(): void }) {
  const { state, dispatch, recipientsForAlert } = useAppState(); const [page, setPage] = useState<MobilePage>("Home"); const [selectedAlertId, setSelectedAlertId] = useState<string | null>(null);
  const contact = state.contacts.find((item) => item.id === state.mobileContactId);
  if (!contact) return <MobileLogin onSwitch={onSwitch}/>;
  const relevantAlerts = state.alerts.filter((alert) => alert.status !== "draft" && recipientsForAlert(alert).some((item) => item.id === contact.id));
  const activeAlerts = relevantAlerts.filter((alert) => alert.status === "active");
  const selected = relevantAlerts.find((alert) => alert.id === selectedAlertId) || null;
  const acknowledge = (alertId: string) => dispatch({ type: "ACK_ALERT", alertId, contactId: contact.id });

  let content: React.ReactNode;
  if (selected) content = <><button className="mobile-back" onClick={() => setSelectedAlertId(null)}>← Back to alerts</button><Card className="mobile-alert-detail"><StatusBadge status={selected.status}/><h2>{selected.title}</h2><small>{selected.type} · {formatDate(selected.sentAt)}</small><p>{selected.message}</p><div className="delivery-channels">Sent through {selected.channels.map((channel) => channel.toUpperCase()).join(", ")}</div></Card>{selected.acknowledgedContactIds.includes(contact.id) ? <Card className="ack-success"><span><Check/></span><div><strong>Alert acknowledged</strong><small>Your confirmation is visible in the administrator workspace.</small></div></Card> : <Button className="mobile-primary-action" variant="danger" onClick={() => acknowledge(selected.id)}>I have received this alert</Button>}</>;
  else if (page === "Home") content = <><header className="mobile-greeting"><div><small>Welcome</small><h1>{contact.name}</h1></div><span>{initials(contact.name)}</span></header>{activeAlerts[0] ? <Card className="mobile-active-alert" onClick={() => setSelectedAlertId(activeAlerts[0].id)}><StatusBadge status="active"/><h2>{activeAlerts[0].title}</h2><p>{activeAlerts[0].message}</p><Button variant="danger">Open alert <ChevronRight size={17}/></Button></Card> : <Card><EmptyState title="No active alerts" description="Official alerts for you will appear here."/></Card>}<div className="mobile-section-heading"><h2>Recent alerts</h2><button onClick={() => setPage("Alerts")}>See all</button></div>{relevantAlerts.length ? <div className="mobile-list">{relevantAlerts.slice(0, 3).map((alert) => <button key={alert.id} onClick={() => setSelectedAlertId(alert.id)}><span><Bell size={18}/></span><div><strong>{alert.title}</strong><small>{formatDate(alert.sentAt)}</small></div><ChevronRight size={17}/></button>)}</div> : <EmptyState title="No alert history" description="Past alerts will appear here."/>}</>;
  else if (page === "Alerts") content = <><header className="mobile-page-header"><h1>My Alerts</h1><p>Active and previous messages sent to you.</p></header>{relevantAlerts.length ? <div className="mobile-list cards">{relevantAlerts.map((alert) => <button key={alert.id} onClick={() => setSelectedAlertId(alert.id)}><span className={alert.status}><Bell size={18}/></span><div><strong>{alert.title}</strong><small>{formatDate(alert.sentAt)} · {alert.acknowledgedContactIds.includes(contact.id) ? "Acknowledged" : "Pending"}</small></div><ChevronRight size={17}/></button>)}</div> : <Card><EmptyState title="No alerts" description="You are up to date."/></Card>}</>;
  else if (page === "My Tree") { const nodes = state.treeNodes.filter((node) => node.name === contact.unit || node.contactId === contact.id); content = <><header className="mobile-page-header"><h1>My Tree</h1><p>Your place in the institutional alert path.</p></header>{nodes.length ? nodes.map((node) => <Card className="tree-assignment" key={node.id}><span><Network/></span><div><small>{node.level}</small><h2>{node.name}</h2><p>{node.contactId === contact.id ? "You are the assigned relay contact." : "You receive alerts through this unit."}</p></div></Card>) : <Card><EmptyState title="No call-tree assignment" description="Ask an administrator to assign your contact to a unit."/></Card>}<Card className="mobile-summary"><h2>Alert responsibility</h2><div><span>Active alerts</span><strong>{activeAlerts.length}</strong></div><div><span>Pending acknowledgment</span><strong>{activeAlerts.filter((alert) => !alert.acknowledgedContactIds.includes(contact.id)).length}</strong></div></Card></>; }
  else content = <><header className="mobile-page-header"><h1>Profile</h1><p>Your locally stored contact record.</p></header><Card className="mobile-profile"><span>{initials(contact.name)}</span><h2>{contact.name}</h2><p>{contact.role} · {contact.unit || "No unit"}</p><dl><div><dt>Phone</dt><dd>{contact.phone}</dd></div><div><dt>Email</dt><dd>{contact.email || "—"}</dd></div><div><dt>Consent</dt><dd>{contact.consent ? "Recorded" : "Pending"}</dd></div></dl></Card><Button variant="secondary" onClick={onSwitch}><Settings size={17}/> Admin workspace</Button><Button variant="danger" onClick={() => dispatch({ type: "MOBILE_LOGOUT" })}><LogOut size={17}/> Sign out</Button></>;

  const nav: Array<{ page: MobilePage; icon: typeof Home }> = [{ page: "Home", icon: Home }, { page: "Alerts", icon: Bell }, { page: "My Tree", icon: Network }, { page: "Profile", icon: User }];
  return <div className="mobile-app"><main className="mobile-content">{content}</main><nav className="mobile-bottom-nav">{nav.map(({ page: item, icon: Icon }) => <button className={page === item && !selected ? "active" : ""} key={item} onClick={() => { setPage(item); setSelectedAlertId(null); }}><Icon size={21}/><span>{item}</span>{item === "Alerts" && activeAlerts.length > 0 && <em>{activeAlerts.length}</em>}</button>)}</nav></div>;
}
